# Generated by Django 2.2.3 on 2020-03-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200328_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='food.UserProfile'),
        ),
    ]
