# Generated by Django 2.2.3 on 2020-03-29 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Restaurant_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.CharField(max_length=100)),
                ('detailed', models.CharField(blank=True, max_length=300, null=True)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('emailAddress', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.UserProfile')),
            ],
        ),
    ]
