# Generated by Django 2.2.3 on 2020-03-30 11:35

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('food', '0005_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='emailAddress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Restaurant_ID',
            new_name='restaurant_ID',
        ),
    ]
