# Generated by Django 2.2.3 on 2020-03-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200330_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='emailAddress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
