# Generated by Django 2.2.3 on 2020-03-31 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20200330_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Restaurant_ID',
            new_name='restaurant_ID',
        ),
    ]
