# Generated by Django 2.2.3 on 2020-03-31 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20200331_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('review_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('comment', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.UserProfile')),
            ],
        ),
    ]
