# Generated by Django 2.2.3 on 2020-04-01 15:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, default='', max_length=100, null=True, size=None),
        ),
    ]
