# Generated by Django 2.2.3 on 2020-04-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_restaurant_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.FileField(null=True, upload_to='C:\\Users\\Jamie Fox\\Documents\\WAD2\\workspace\\glasgow_food_guide\\media'),
        ),
    ]
