# Generated by Django 2.2.3 on 2020-04-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_auto_20200403_0336'),
        ('food', '0020_auto_20200402_2103'),
    ]

    operations = [
    ]
